#!/bin/bash
# ⚡ NetConfig - First Time Setup
# Run: bash setup.sh

set -e
clear

echo "╔══════════════════════════════════════════════╗"
echo "║        ⚡ NetConfig v1.0.0 Setup            ║"
echo "║     Network Device Management Platform      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed."
    echo "   Install: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "❌ Docker Compose is not installed."
    echo "   Install: sudo apt install docker-compose-v2"
    exit 1
fi

echo "✅ Docker and Docker Compose detected"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 1: Generate Security Keys"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

echo "✅ Secret key generated"
echo "✅ Fernet encryption key generated"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 2: Application Settings"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# App port
read -p "🌐 App port [5000]: " APP_PORT
APP_PORT=${APP_PORT:-5000}

# SSH timeout
read -p "⏱️  SSH connection timeout in seconds [30]: " SSH_TIMEOUT
SSH_TIMEOUT=${SSH_TIMEOUT:-30}

# Gunicorn workers
echo "ℹ️  Use 1 worker to maintain SSH session persistence"
read -p "👷 Gunicorn workers [1]: " GUNICORN_WORKERS
GUNICORN_WORKERS=${GUNICORN_WORKERS:-1}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 3: UniFi Controller (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  If you have a UniFi controller (UDM-Pro, Cloud Key, etc.)"
echo "  enter the details below. Otherwise press Enter to skip."
echo ""

read -p "🔌 Do you have a UniFi controller? (y/n) [n]: " HAS_UNIFI
HAS_UNIFI=${HAS_UNIFI:-n}

if [[ "$HAS_UNIFI" =~ ^[Yy]$ ]]; then
    read -p "🌐 UniFi Controller URL [https://192.168.1.1]: " UNIFI_URL
    UNIFI_URL=${UNIFI_URL:-https://192.168.1.1}

    read -p "👤 UniFi Username [admin]: " UNIFI_USER
    UNIFI_USER=${UNIFI_USER:-admin}

    read -sp "🔑 UniFi Password: " UNIFI_PASS
    echo ""

    read -p "📍 UniFi Site [default]: " UNIFI_SITE
    UNIFI_SITE=${UNIFI_SITE:-default}

    echo ""
    echo "⚠️  Note: SSO/MFA accounts are NOT supported."
    echo "   Use a LOCAL admin account on the controller."
else
    UNIFI_URL=""
    UNIFI_USER=""
    UNIFI_PASS=""
    UNIFI_SITE="default"
fi
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 4: SNMP Configuration (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  SNMP is used to monitor CPU, memory, temperature,"
echo "  interface traffic, and hardware status."
echo ""

read -p "📡 Do you want to enable SNMP monitoring? (y/n) [y]: " HAS_SNMP
HAS_SNMP=${HAS_SNMP:-y}

if [[ "$HAS_SNMP" =~ ^[Yy]$ ]]; then
    read -p "🔑 SNMP Community String [public]: " SNMP_COMMUNITY
    SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

    read -p "📋 SNMP Version (2c/3) [2c]: " SNMP_VERSION
    SNMP_VERSION=${SNMP_VERSION:-2c}

    read -p "🔌 SNMP Port [161]: " SNMP_PORT
    SNMP_PORT=${SNMP_PORT:-161}

    read -p "⏱️  SNMP Timeout in seconds : " SNMP_TIMEOUT_VAL
    SNMP_TIMEOUT_VAL=${SNMP_TIMEOUT_VAL:-5}

    read -p "🔄 SNMP Retries : " SNMP_RETRIES
    SNMP_RETRIES=${SNMP_RETRIES:-2}
else
    SNMP_COMMUNITY="public"
    SNMP_VERSION="2c"
    SNMP_PORT="161"
    SNMP_TIMEOUT_VAL="5"
    SNMP_RETRIES="2"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 5: Default SSH Credentials (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  These are used as defaults when adding new devices."
echo "  You can override per-device in the web UI."
echo ""

read -p "👤 Default SSH username [admin]: " DEFAULT_SSH_USER
DEFAULT_SSH_USER=${DEFAULT_SSH_USER:-admin}

read -sp "🔑 Default SSH password (leave blank for none): " DEFAULT_SSH_PASS
echo ""

read -p "🔌 Default SSH port [22]: " DEFAULT_SSH_PORT
DEFAULT_SSH_PORT=${DEFAULT_SSH_PORT:-22}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 6: Writing Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Write .env file
cat > .env << ENVEOF
# ⚡ NetConfig Configuration
# Generated by setup.sh on $(date)

# Security Keys (DO NOT SHARE)
SECRET_KEY=${SECRET_KEY}
FERNET_KEY=${FERNET_KEY}

# Application
FLASK_ENV=production
DATABASE_URL=sqlite:////app/instance/netconfig.db
REDIS_URL=redis://localhost:6379/0
APP_PORT=${APP_PORT}
SSH_TIMEOUT=${SSH_TIMEOUT}
GUNICORN_WORKERS=${GUNICORN_WORKERS}

# UniFi Controller
UNIFI_CONTROLLER_URL=${UNIFI_URL}
UNIFI_USERNAME=${UNIFI_USER}
UNIFI_PASSWORD=${UNIFI_PASS}
UNIFI_SITE=${UNIFI_SITE}

# Default SSH Credentials
DEFAULT_SSH_USERNAME=${DEFAULT_SSH_USER}
DEFAULT_SSH_PASSWORD=${DEFAULT_SSH_PASS}
DEFAULT_SSH_PORT=${DEFAULT_SSH_PORT}

# SNMP Configuration
SNMP_COMMUNITY=${SNMP_COMMUNITY}
SNMP_VERSION=${SNMP_VERSION}
SNMP_PORT=${SNMP_PORT}
SNMP_TIMEOUT=${SNMP_TIMEOUT_VAL}
SNMP_RETRIES=${SNMP_RETRIES}

ENVEOF

echo "✅ .env file created"

# Create instance directory
mkdir -p instance
echo "✅ Instance directory created"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 7: Build & Launch"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "🚀 Build and start NetConfig now? (y/n) [y]: " DO_BUILD
DO_BUILD=${DO_BUILD:-y}

if [[ "$DO_BUILD" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Building containers... (this may take a few minutes)"
    echo ""
    sudo docker compose up -d --build

    echo ""
    echo "⏳ Waiting for services to start..."
    sleep 5

    # Health check
    if curl -s http://localhost:${APP_PORT}/health > /dev/null 2>&1; then
        echo "✅ NetConfig is running!"
    else
        echo "⚠️  App may still be starting. Check: sudo docker compose logs netconfig"
    fi
else
    echo ""
    echo "To start later, run:"
    echo "  sudo docker compose up -d --build"
fi

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║          ✅ Setup Complete!                  ║"
echo "╠══════════════════════════════════════════════╣"
echo "║                                              ║"
echo "║  🌐 Access: http://localhost:${APP_PORT}          ║"
echo "║                                              ║"
echo "║  📋 Commands:                                ║"
echo "║    Start:   sudo docker compose up -d        ║"
echo "║    Stop:    sudo docker compose down         ║"
echo "║    Logs:    sudo docker compose logs -f      ║"
echo "║    Rebuild: sudo docker compose up -d --build║"
echo "║                                              ║"
echo "║  ⚠️  Keep .env file secure — it contains     ║"
echo "║     your encryption keys and passwords!      ║"
echo "║                                              ║"
echo "╚══════════════════════════════════════════════╝"

